"""The published OpenAPI spec is what agents read to call this API.

These lock the properties an LLM function-calling client depends on: a unique,
readable operationId per operation, a description on every operation, typed
response schemas on the public endpoints, and the server/tag/contact metadata
that tells a caller where the API lives.
"""

import pytest
from httpx import AsyncClient

from app.main import ROBOTS_TXT, app

HTTP_METHODS = ("get", "post", "put", "patch", "delete")


def _operations(spec):
    for path, item in spec["paths"].items():
        for method, operation in item.items():
            if method in HTTP_METHODS:
                yield path, method, operation


@pytest.fixture(scope="module")
def spec():
    return app.openapi()


def test_operation_ids_are_unique(spec):
    ids = [op["operationId"] for _, _, op in _operations(spec)]
    duplicates = {i for i in ids if ids.count(i) > 1}
    assert not duplicates, f"duplicate operationIds: {sorted(duplicates)}"


def test_operation_ids_are_readable(spec):
    """Not FastAPI's autogenerated 'name_path_method' form."""
    for path, method, op in _operations(spec):
        op_id = op["operationId"]
        assert op_id == op_id.lower(), f"{op_id} is not lowercase"
        assert not op_id.endswith(f"_{method}"), (
            f"{op_id} still carries the autogenerated method suffix ({method} {path})"
        )
        assert "__" not in op_id


def test_every_operation_has_a_description(spec):
    missing = [
        f"{m.upper()} {p}" for p, m, op in _operations(spec) if not op.get("description")
    ]
    assert not missing, f"operations without a description: {missing}"


def test_every_operation_declares_a_success_response(spec):
    for path, method, op in _operations(spec):
        codes = [c for c in op.get("responses", {}) if c.startswith("2")]
        assert codes, f"{method.upper()} {path} declares no 2xx response"


def test_public_pricing_endpoints_have_typed_response_schemas(spec):
    """A schema-less 200 tells a function-calling client nothing about the payload."""
    public_paths = [
        "/v1/pricing",
        "/v1/pricing/{model_name}",
        "/v1/pricing/deprecations",
        "/v1/pricing/sync/status",
    ]
    for path in public_paths:
        schema = spec["paths"][path]["get"]["responses"]["200"]["content"][
            "application/json"
        ]["schema"]
        assert schema.get("$ref"), f"{path} has an untyped 200 response"


def test_path_parameters_are_typed(spec):
    for path, method, op in _operations(spec):
        for param in op.get("parameters", []):
            assert param.get("schema"), (
                f"{method.upper()} {path} parameter {param.get('name')} has no schema"
            )


def test_spec_declares_servers_contact_and_license(spec):
    urls = [s["url"] for s in spec["servers"]]
    assert "https://api.agentcost.tech" in urls
    assert spec["info"]["contact"]["email"]
    assert spec["info"]["license"]["name"] == "MIT"
    assert spec["info"]["termsOfService"].startswith("https://")


def test_every_tag_in_use_is_described(spec):
    described = {t["name"] for t in spec.get("tags", [])}
    used = {tag for _, _, op in _operations(spec) for tag in op.get("tags", [])}
    assert used <= described, f"tags used but not described: {sorted(used - described)}"
    for tag in spec["tags"]:
        assert tag.get("description"), f"tag {tag['name']} has no description"


@pytest.mark.asyncio
async def test_openapi_json_is_served(client: AsyncClient):
    response = await client.get("/openapi.json")
    assert response.status_code == 200
    assert response.json()["info"]["title"]


def test_robots_allows_the_machine_readable_surface():
    """A blanket Disallow was hiding the spec from every crawler and agent."""
    assert "Allow: /openapi.json" in ROBOTS_TXT
    assert "Allow: /docs" in ROBOTS_TXT
    assert "Allow: /v1/pricing" in ROBOTS_TXT
    assert "Disallow: /" in ROBOTS_TXT


@pytest.mark.asyncio
async def test_robots_txt_endpoint_serves_it(client: AsyncClient):
    response = await client.get("/robots.txt")
    assert response.status_code == 200
    assert "Allow: /openapi.json" in response.text
